/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ztmatheddskgkttyhsfu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bWF0aGVkZHNrZ2t0dHloc2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NjUwNzcsImV4cCI6MjA4MjI0MTA3N30.YtSv5xnf-hifgdR8T_Z4-v5fNHTW6YngVegVD_zVnYc"